name: PC28 Timer

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  visit:
    runs-on: ubuntu-latest
    steps:
      - name: 访问目标链接
        run: |
          curl -H "User-Agent: Mozilla/5.0" \
            'http://pc28.asia/index.php?action=refresh&code=pc28@2026'
